name: iosApp
options:
  bundleIdPrefix: com.wojdor.memolki
  deploymentTarget:
    iOS: "13.0"
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_LANGUAGE: en
    ENABLE_USER_SCRIPT_SANDBOXING: NO
targets:
  iosApp:
    type: application
    platform: iOS
    sources:
      - path: iosApp
    info:
      path: iosApp/Info.plist
      properties:
        UILaunchScreen: {}
        CFBundleDisplayName: Memolki
        CFBundleShortVersionString: "1.3.35"
        CFBundleVersion: "1003035"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.wojdor.memolki.fruithalf
        MARKETING_VERSION: "1.3.35"
        CURRENT_PROJECT_VERSION: "1003035"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        DEVELOPMENT_ASSET_PATHS: "\"iosApp/Preview Content\""
        ENABLE_PREVIEWS: YES
        TARGETED_DEVICE_FAMILY: "1,2"
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
