name: Pull Request Workflow

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@cfd5498da48e3451cad87051c6102b44984c3118 # v4

      - name: set up JDK 17
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew app:assembleFruitHalf --stacktrace --no-daemon

      - name: Upload APKs
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: apks
          path: '**/build/outputs/apk/**/*.apk'
