name: Merge Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@e4a7a75220cde05e60d5b035176b61b7593c6f83 # v3

      - name: Build with Gradle
        run: ./gradlew app:assembleFruitHalf --stacktrace --no-daemon --build-cache

      - name: Upload APKs
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: apks
          path: '**/build/outputs/apk/**/*.apk'
