name: Pull Request Workflow

on:
  pull_request_target:

jobs:
  tests-execution:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.head_ref, 'chore/') }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run unit tests
        run: ./gradlew testFruitHalfDebugUnitTest --no-daemon --build-cache

  unit-test:
    needs: tests-execution
    runs-on: ubuntu-latest
    if: ${{ always() && (needs.tests-execution.result == 'success' || needs.tests-execution.result == 'skipped') }}
    steps:
      - name: All checks passed
        run: echo "All checks passed or were intentionally skipped."
