name: Pull Request Workflow

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@41ad77ca97e46ee2e825d5e6b9a95d8169fcc44c # v4.4.2

      - name: Run unit tests
        run: ./gradlew testFruitHalfDebugUnitTest --no-daemon --build-cache
